In [1]:
import pandas as pd
import numpy as np
import spacy
import scipy as sp
import sklearn

In [17]:
df = pd.read_csv('manually_fixed.csv')

In [18]:
df.head()

newdf= df[['failure_mode_tm', 'long_text_notification']]

In [19]:
newdf.head()
newdf.shape

(1532, 2)

In [20]:
df2 = newdf.dropna()
df.shape
#newdf1.head()

(1532, 31)

In [21]:
df2.shape

(845, 2)

In [22]:
df2.head()

  failure_mode_tm                             long_text_notification
1            Worn  18.04.2016 01:58:07 UTC Ronald Piggott (PIGGR9...
2            Worn  06.06.2016 14:34:43 UTC Ronald Piggott (PIGGR9...
3            Worn  27.07.2016 13:34:51 UTC Owen Nugent (NUGEO91) ...
4          Failed  15.10.2013 02:57:03 Stuart Mau (MAUST)    Defi...
5            Worn  09.01.2017 15:54:12 UTC Kris Day (DAYKR9) Phon...

In [23]:
myvar = df2['long_text_notification'].loc[3]
myvar

'27.07.2016 13:34:51 UTC Owen Nugent (NUGEO91)    Brief description of what occurred (e.g. basic sequence of events and impacts avoiding the use of personnel names):  Replace Gear Selector   *     Define work requirements; including known materials specialist labour special tools that are required:  10855529 x 1 12-4 for 3 hours   *     *    '

In [24]:
# Preprocessing 3:
# Remove web related garbage
# Remove any words with anything other than characters (a-z|A-Z)

def remove_garbage(list_words):
    new_list = []
    for word in list_words:
        if word.isalpha(): new_list.append(word)        
    return new_list

In [25]:
def remove_template(str_input):
    var2 = str_input[str_input.find('Brief'):]
    var3 = var2[var2.find(':') + 1:]
    var4 = var3[:var3.find("Define")] + var3[var3.find(':')+ 1:]
    var5 = remove_garbage(var4.split())
    var6 = [ x.lower() for x in  var5 if len(x) >1 ]
    var7 = ' '.join(var6)
    
    return var7

In [26]:
df2['clean_text'] = df2.long_text_notification.apply(lambda words: remove_template(words))

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
df2.head()

,failure_mode_tm,long_text_notification,clean_text
1,Worn,18.04.2016 01:58:07 UTC Ronald Piggott (PIGGR9...,gear changer not working needs replacing elect...
2,Worn,06.06.2016 14:34:43 UTC Ronald Piggott (PIGGR9...,gear selector playing up needs replacing elect...
3,Worn,27.07.2016 13:34:51 UTC Owen Nugent (NUGEO91) ...,replace gear selector for hours
4,Failed,15.10.2013 02:57:03 Stuart Mau (MAUST) Defi...,
5,Worn,09.01.2017 15:54:12 UTC Kris Day (DAYKR9) Phon...,whilst completing sos operator reported fault ...

In [28]:
df3 = df2[df2['clean_text'].apply(lambda x: len(x)>0)]

#df3.to_csv("sample.csv")
df3.head()

,failure_mode_tm,long_text_notification,clean_text
1,Worn,18.04.2016 01:58:07 UTC Ronald Piggott (PIGGR9...,gear changer not working needs replacing elect...
2,Worn,06.06.2016 14:34:43 UTC Ronald Piggott (PIGGR9...,gear selector playing up needs replacing elect...
3,Worn,27.07.2016 13:34:51 UTC Owen Nugent (NUGEO91) ...,replace gear selector for hours
5,Worn,09.01.2017 15:54:12 UTC Kris Day (DAYKR9) Phon...,whilst completing sos operator reported fault ...
7,Worn,09.01.2018 13:23:33 UTC Rory Bean (BEANRX) ...,faulty selector lever changed out selector lev...

In [29]:
#Remove Stop words
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import PorterStemmer, WordNetLemmatizer
porter_stemmer = PorterStemmer()
stemmer = SnowballStemmer("english")
stop = stopwords.words('english')

df3['stop_words_removed'] = df3['clean_text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [16]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [30]:
def stem_sentences(sentence):
    tokens = sentence.split()
    stemmed_tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

df3['stemmed'] = df3['stop_words_removed'].apply(stem_sentences)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [31]:
df3.head()

,failure_mode_tm,long_text_notification,clean_text,stop_words_removed,stemmed
1,Worn,18.04.2016 01:58:07 UTC Ronald Piggott (PIGGR9...,gear changer not working needs replacing elect...,gear changer working needs replacing elect hrs,gear changer work need replac elect hrs
2,Worn,06.06.2016 14:34:43 UTC Ronald Piggott (PIGGR9...,gear selector playing up needs replacing elect...,gear selector playing needs replacing elect hrs,gear selector play need replac elect hrs
3,Worn,27.07.2016 13:34:51 UTC Owen Nugent (NUGEO91) ...,replace gear selector for hours,replace gear selector hours,replac gear selector hour
5,Worn,09.01.2017 15:54:12 UTC Kris Day (DAYKR9) Phon...,whilst completing sos operator reported fault ...,whilst completing sos operator reported fault ...,whilst complet sos oper report fault gear leav...
7,Worn,09.01.2018 13:23:33 UTC Rory Bean (BEANRX) ...,faulty selector lever changed out selector lev...,faulty selector lever changed selector lever f...,faulti selector lever chang selector lever fit...

In [32]:
#Building the model
df3.to_csv('hello.csv')

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer


tp_vectorizer = TfidfVectorizer(min_df = 1, binary = True)

train_X = df3.iloc[:, :]['stemmed']
tp_train_X = tp_vectorizer.fit_transform(train_X)
train_Y = df3.iloc[:, :]['failure_mode_tm']

In [34]:
df3['failure_mode_tm'].value_counts()

worn          185
Worn          175
Failed        114
Inoperable     17
damaged        13
Damaged        10
Fails           5
failed          5
output          3
burnt           1
cracked         1
Wears           1
Name: failure_mode_tm, dtype: int64

In [35]:
df3['target'] = df3['failure_mode_tm'].apply(lambda x: x.lower())

df3['target_2'] = df3['target'].str.replace('fails', 'failed')

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [36]:
df3.head()
df3['target_2'].value_counts()

worn          360
failed        124
damaged        23
inoperable     17
output          3
burnt           1
cracked         1
wears           1
Name: target_2, dtype: int64

In [37]:
df4 = df3.reset_index(drop = True)

In [38]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 7 columns):
failure_mode_tm           530 non-null object
long_text_notification    530 non-null object
clean_text                530 non-null object
stop_words_removed        530 non-null object
stemmed                   530 non-null object
target                    530 non-null object
target_2                  530 non-null object
dtypes: object(7)
memory usage: 29.1+ KB

In [39]:
from sklearn import svm
#clf = svm.SVC(gamma='scale')

clf= svm.SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
#clf.fit(tp_train_X, train_Y)

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer


tp_vectorizer = TfidfVectorizer(min_df = 1)

train_X = df4.iloc[:, :]['stop_words_removed']
tp_train_X = tp_vectorizer.fit_transform(train_X)
train_Y = df4.iloc[:, :]['target_2']

In [258]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
 
mykFold = KFold(n_splits=5, random_state=None, shuffle=False)
for train_index, test_index in mykFold.split(tp_train_X):
#    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = tp_train_X[train_index], tp_train_X[test_index]
    y_train, y_test = train_Y[train_index], train_Y[test_index]

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    acc= accuracy_score(y_test, y_pred)
    print(acc)
#     break

0.7075471698113207
0.7641509433962265
0.6698113207547169
0.6415094339622641
0.6132075471698113

In [259]:
#On new data

tp_test_X = tp_vectorizer.transform(test_X)
clf.predict(tp_test_X)

array(['worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn', 'worn',
       'worn', 'worn', 'worn', 'worn', 'worn'], dtype=object)

In [250]:
newdf  = pd.read_csv('sample_test.csv')
newdf.head()

,Unnamed: 0,failure_mode_tm,stop_words_removed
0,1,Worn,gear changer working needs replacing elect hrs
1,2,Worn,gear selector playing needs replacing elect hrs
2,3,Worn,replace gear selector hours
3,5,Worn,whilst completing sos operator reported fault ...
4,7,Worn,faulty selector lever changed selector lever f...

In [264]:
test_X = newdf['stop_words_removed']
tp_test_X = tp_vectorizer.transform(test_X)
predictions = clf.predict(tp_test_X)
confidence = clf.predict_proba(tp_test_X)

In [270]:
type(confidence)
#print(confidence.classes_[order[:, -5:]])
df = pd.DataFrame(confidence)
df

            0         1         2         3         4         5         6
0    0.002622  0.049546  0.312931  0.009581  0.005616  0.003183  0.616520
1    0.002321  0.041827  0.101783  0.006540  0.003547  0.003133  0.840849
2    0.002280  0.040811  0.067008  0.006596  0.003499  0.002433  0.877372
3    0.002404  0.045207  0.132962  0.008378  0.004588  0.003264  0.803195
4    0.003497  0.037078  0.194065  0.041272  0.005972  0.003378  0.714738
5    0.002339  0.039581  0.133637  0.012784  0.003300  0.001913  0.806447
6    0.004635  0.052238  0.828478  0.019905  0.011004  0.004859  0.078881
7    0.004605  0.045101  0.606569  0.016393  0.015210  0.003919  0.308202
8    0.002193  0.041178  0.133349  0.013409  0.004052  0.001993  0.803826
9    0.002283  0.049966  0.163630  0.014166  0.003649  0.001902  0.764404
10   0.002362  0.040708  0.070541  0.005987  0.003729  0.002659  0.874012
11   0.002391  0.048826  0.106703  0.009567  0.003457  0.002350  0.826706
12   0.002175  0.040892  0.165455  0.016655  0.004029  0.001911  0.768884
13   0.002904  0.040269  0.103938  0.028928  0.005948  0.003677  0.814335
14   0.002281  0.045999  0.131706  0.008380  0.003732  0.002118  0.805783
15   0.002489  0.042469  0.090467  0.013062  0.004287  0.001850  0.845376
16   0.002550  0.046142  0.113385  0.021010  0.006191  0.002107  0.808616
17   0.002359  0.038816  0.106229  0.015301  0.004536  0.002474  0.830285
18   0.002701  0.046434  0.288727  0.019815  0.006843  0.002285  0.633193
19   0.002511  0.044897  0.100429  0.018651  0.006085  0.002071  0.825355
20   0.003394  0.059442  0.422925  0.026045  0.008593  0.003027  0.476575
21   0.002619  0.051551  0.213739  0.022239  0.006875  0.002188  0.700789
22   0.002312  0.042738  0.113051  0.010138  0.004415  0.002181  0.825166
23   0.002325  0.039667  0.099937  0.011244  0.003019  0.001726  0.842082
24   0.006010  0.067150  0.844307  0.032319  0.014776  0.006158  0.029280
25   0.006010  0.067150  0.844307  0.032319  0.014776  0.006158  0.029280
26   0.005775  0.063740  0.784495  0.018749  0.011866  0.004738  0.110638
27   0.002151  0.043065  0.061056  0.010128  0.001903  0.001965  0.879733
28   0.002064  0.034379  0.062087  0.006760  0.002037  0.001612  0.891061
29   0.002714  0.062920  0.226776  0.011648  0.004031  0.002457  0.689454
..        ...       ...       ...       ...       ...       ...       ...
79   0.002481  0.070173  0.107419  0.014421  0.005113  0.001999  0.798394
80   0.006364  0.079157  0.824002  0.033650  0.014293  0.006589  0.035944
81   0.006364  0.079157  0.824002  0.033650  0.014293  0.006589  0.035944
82   0.006364  0.079157  0.824002  0.033650  0.014293  0.006589  0.035944
83   0.002248  0.048974  0.109261  0.014776  0.004295  0.001817  0.818631
84   0.002215  0.046222  0.089864  0.012163  0.004124  0.001779  0.843631
85   0.002203  0.044865  0.113570  0.011636  0.004210  0.001797  0.821720
86   0.002178  0.040919  0.057347  0.006478  0.003245  0.001865  0.887967
87   0.002326  0.040028  0.110777  0.016568  0.003981  0.001875  0.824445
88   0.004362  0.067117  0.540419  0.033148  0.009807  0.004178  0.340970
89   0.007600  0.081272  0.816289  0.044849  0.017552  0.007457  0.024981
90   0.007600  0.081272  0.816289  0.044849  0.017552  0.007457  0.024981
91   0.002290  0.044591  0.099388  0.013745  0.004173  0.001900  0.833913
92   0.002369  0.036557  0.100142  0.017628  0.005393  0.001991  0.835920
93   0.002444  0.042430  0.133365  0.016018  0.005509  0.001853  0.798381
94   0.002775  0.042873  0.104494  0.033634  0.004564  0.002201  0.809458
95   0.002329  0.044800  0.135788  0.017780  0.005474  0.001912  0.791916
96   0.002461  0.034625  0.222557  0.013602  0.006786  0.002195  0.717774
97   0.002262  0.049823  0.142045  0.013585  0.004430  0.002012  0.785844
98   0.002107  0.047660  0.100483  0.010502  0.002240  0.002122  0.834887
99   0.002107  0.047660  0.100483  0.010502  0.002240  0.002122  0.834887
100  0.002273  0.036805  0.086596  0.015493  0.003724  0.001931  0.853179
101  0.002293  0.063226  0.076058  0.013844  0.002969  0.002210  0.839401
102  0.002293  0.063226  0.076058  0.013844  0.002969  0.002210  0.839401
103  0.002293  0.063226  0.076058  0.013844  0.002969  0.002210  0.839401
104  0.002293  0.063226  0.076058  0.013844  0.002969  0.002210  0.839401
105  0.002349  0.047173  0.102277  0.014293  0.004953  0.001921  0.827035
106  0.002212  0.036910  0.063344  0.009271  0.004058  0.002028  0.882177
107  0.002212  0.036910  0.063344  0.009271  0.004058  0.002028  0.882177
108  0.002187  0.055068  0.054901  0.013088  0.003823  0.001817  0.869116

[109 rows x 7 columns]

In [271]:
T#this is how the final output shoukd be
newdf['predictions'] = predictions
#newdf['Probability'] = confidence

newdf

,Unnamed: 0,failure_mode_tm,stop_words_removed,predictions
0,1,Worn,gear changer working needs replacing elect hrs,worn
1,2,Worn,gear selector playing needs replacing elect hrs,worn
2,3,Worn,replace gear selector hours,worn
3,5,Worn,whilst completing sos operator reported fault ...,worn
4,7,Worn,faulty selector lever changed selector lever f...,worn
5,8,Worn,maintainer blower mototr needs investigation f...,worn
6,9,Failed,horn replace created sparky hours,worn
7,10,Failed,fitter hours,worn
8,11,Worn,handle hoist peice hex steel raised notificati...,worn
9,14,Worn,propulsion checked faults found counts directi...,worn
10,15,Worn,gear selector,worn
11,16,Worn,maintainer diagnosed gear selector needs notif...,worn
12,17,Worn,machine faulted grid blower delta inspected gr...,worn
13,18,Worn,replace faulty gear,worn
14,19,Worn,gear selector button sticking becoming hard ch...,worn
15,20,Worn,replace stair elec motor fitter,worn
16,22,Worn,acc deck,worn
17,23,Worn,maintenance found gear selector lever issue pa...,worn
18,26,Worn,fwd contoller working,worn
19,27,Worn,lhr mudflap support torn half mudflap well par...,worn
20,29,Worn,front truck damaged due crash photo attached,worn
21,31,Worn,park brakes failed,worn
22,35,Worn,gear selector one one hour one,worn
23,62,worn,alternator brushes blower brushes replace worn...,worn
24,74,Failed,inverter fault truck gone ramp numerous times ...,worn
25,75,Failed,inverter fault truck gone ramp numerous times ...,worn
26,92,Failed,electric horn open circuit pn task take auto e...,worn
27,123,worn,lecky hrs change alternator brushes made notif...,worn
28,124,worn,electrician hours brushes blower motor brushes...,worn
29,134,Damaged,rp contactor replace checked sparky hours nil nil,worn
...,...,...,...,...
79,276,Worn,lhr reverse light broken autelect,worn
80,277,Failed,grid resistors front rhs grid box truck taken ...,worn
81,278,Failed,grid resistors front rhs grid box truck taken ...,worn
82,279,Failed,grid resistors front rhs grid box truck taken ...,worn
83,280,Worn,conatact tips replace full kit electrician nil...,worn
84,283,Worn,conatact tips replace full rp kit electrician ...,worn
85,284,Worn,conatact tips replaced full rp contact tip kit...,worn
86,293,Worn,service noted rp contactor tips worn notificat...,worn
87,294,worn,jeff peterson work carried komatsu hv checked ...,worn
88,296,Failed,failed rdb recitifer diode clean cabinets repl...,worn
89,299,Failed,truck propulsion restriction due failure inver...,worn
90,300,Failed,truck propulsion restriction due failure inver...,worn
91,304,Worn,service contact tips noted worn past servicabl...,worn
92,305,Worn,week service noticed wear needs electrician,worn
93,306,Worn,week service noticed visual inspection rp cont...,worn
94,307,worn,service number hv alternator brushes measure a...,worn
95,312,Worn,tips sad go till next service lekky hours set ...,worn
96,313,worn,hv electrician hours,worn
97,314,Worn,found service contact tips need replacing none...,worn
98,320,worn,alternator brushes made notification lecky hrs...,worn
99,321,worn,alternator brushes made notification lecky hrs...,worn
100,322,worn,insepcted alternator week serivce noticed thre...,worn
101,327,worn,inspection found following needed replacing in...,worn
102,328,worn,inspection found following needed replacing in...,worn
103,329,worn,inspection found following needed replacing in...,worn
104,330,Worn,inspection found following needed replacing in...,worn
105,331,Worn,replace rp contact one one hv sparky one,worn
106,332,worn,found one alternator brushes need replacing rp...,worn
107,335,Worn,found one alternator brushes need replacing rp...,worn
108,346,worn,replace arc chutes next maint hv electrician two,worn

#Further Instructions:

Write the final output of the predictions to a CSV file. In the output the predicted class, the propability (condifdence of the prediction) should be appneded to the test data csv file as you have seen above in the dummy example

For this task:

**Try and build about 3 or 4 different models (ignore basic models like SVM, Logistic Regression, Random Forest), I have already build those models. We will use these models as baseline

**IF you want to use these models then you can try an esemble model where you stack 3 or four different classifiers to see what we can get.

**But focus on models that use neural nets, LSTM etc like what we discussed the other time.

**Behind schedule for this competetion so Please get me something ASAP. 

**Create a git hub repo with all the instructions in codes and it ans share it with me.

In [42]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split